### ISSUE TITLE
New Microsoft Teams classic.app forcing Office365 app installs

### ISSUE THREAD

**Issue by rfrankIC** [microsoft/shell-intune-samples#109]
With the recent change to Teams on macOS, changing the app name to **Microsoft Teams classic.app**, we are seeing the script force close and reinstall the entire suite. 

**Microsoft Teams.app** is listed in the app array (line 350), but the application's name is now **Microsoft Teams classic.app** which means every time the script runs it will reinstall the whole suite. I just removed Teams from the app array to alleviate the problem.

**Comment by patthew** [comment]
I encountered this as well, but I just removed the ".app" and added a wildcard to the end of that line:

"/Applications/Microsoft Teams"*

**Comment by theneiljohnson** [comment]
Should be resolved in both the Office sample and Teams sample now. Apologies for the impact, it caught us off guard too.
