### ISSUE TITLE
Office for Mac does not create any log

### ISSUE THREAD

**Issue by ClausPD** [microsoft/shell-intune-samples#162]
Hello everyone

I have tried to run this script here and the only thing is that it installs an office package but does not leave any log in IntuneScripts and when I try to run them in the terminal it says error in line 512 with this command [ exec & > >(tee -a "$log") ] and if I remove it I can run it without problems, but how do I get it to create a log of installation?

I have filled it as there is a bump to Intune but no log comes out.

**Comment by theneiljohnson** [comment]
It seems fine to me, are you running via sudo or root from Intune?

**Comment by theneiljohnson** [comment]
![Image](https://github.com/user-attachments/assets/179b9091-eac2-4981-854c-5dc305b66e85)
See if this helps

**Comment by ClausPD** [comment]
I'm not sure if I'm doing it right but when I try to run it I get the error, what am I typing wrong?![Image](https://github.com/user-attachments/assets/83286b2d-1133-40c9-a000-ffec9efca0fa)

**Comment by theneiljohnson** [comment]
Can you open it and have a look at the script? It doesn't look like it's downloaded correctly.

**Comment by theneiljohnson** [comment]
Can you try head -n 10 installOffice365Pro.sh please. I suspect you've downloaded a HTML page or it's been mangled on Windows.

**Comment by ClausPD** [comment]
okay, I didn't quite understand that, but I downloaded it via my Macbook which I use to test with, so how do I write it - 10 or how do I do it because I don't understand it right

**Comment by ClausPD** [comment]
I just get an error that the folder 10 is not there, what I write is sudo -n 10 /downloads/installOffice365.sh

So what should I write?![Image](https://github.com/user-attachments/assets/c32004eb-66cf-429d-9f8b-e03dc7ef98ff)

**Comment by theneiljohnson** [comment]
type this command, nothing else, no sh, no . nothing... just type exactly these letters into terminal and press enter.

**head -n 10 $HOME/Downloads/installOffice365Pro.sh**

**Comment by ClausPD** [comment]
I haft try ir out and Can read it, show if i want to running it what shall I type…? Do I need to login as root before et well work in terminal

**Comment by theneiljohnson** [comment]
No, just paste the output of the command.

**Comment by theneiljohnson** [comment]
Oh, actually I just noticed from your screen shot that you're running the command really weirdly. You literally just need sudo ./script.sh you don't need sh.

So.. if you were in the same directory you'd type **sudo ./installOffice365Pro.sh** 

-OR-

**sudo $HOME/Downloads/installOffice365Pro.sh**

**Comment by ClausPD** [comment]
Hi Neil
I have now tried it out and can tell you that it works now, the script now creates a log file inside the IntuneScript folder and have tested it with some other scripts such as Filezilla and Google Drive.

as I have learned, you must use the command (chmod -x) to verify the files before you can use them and after that you can upload them to Intune.

So thank you for your good help in teaching me how to understand it when it is a mac computer :-)

thank you very much for your good help... .

**Comment by theneiljohnson** [comment]
No worries, glad it's working for you. I'll close this now.
