### ISSUE TITLE
add || exit 

### ISSUE THREAD

**Issue by marckerr** [microsoft/shell-intune-samples#18]
https://github.com/microsoft/shell-intune-samples/blob/23a69bbfc7551626fe6fb6fa7e080b2e8585a4f9/Apps/Defender/installDefender.sh#L267

Some references suggest using 'cd' with  '|| exit' incase CD fails
https://github.com/koalaman/shellcheck/wiki/SC2164

**Comment by theneiljohnson** [comment]
I added a few extra checks in to handle this. Thanks for the feedback.
