### ISSUE TITLE
Function "waitForProcess" require improvement

### ISSUE THREAD

**Issue by 3apa3a-b-ta3e** [microsoft/shell-intune-samples#19]
Currently it uses this check to determinate if process is running or not
`ps aux | grep "$processName" | grep -v grep`
which is generally fine, but when it checks for just **curl** there might be issues, coz other processes (like Google Drive) may use same word **curl** in their full command line, so script will never ends waiting for curl exit :-(

**Comment by 3apa3a-b-ta3e** [comment]
Well, actually we can fix it by passing **/curl** to that function (inside _downloadApp_)

**Comment by theneiljohnson** [comment]
Hmm, that's interesting, can you share the output from ps aux | grep "curl" with Google Drive running?

**Comment by 3apa3a-b-ta3e** [comment]
It produced A LOT of output, but source of my issue is here
`/Applications/Google Drive.app/Contents/MacOS/crashpad_handler --annotation=curl_proxy_authentication=on`
(to be honest - there is much more cli options, just posting relevant one)

**Comment by theneiljohnson** [comment]
Thanks, i'll take a look tomorrow and see if I can make it a little more robust.

**Comment by theneiljohnson** [comment]
I've pushed out some updates. I've basically just changed the grep to look for 'curl -f' which should appear on all of the download calls from these scripts.

I've tested against Google Drive and it seems to behave. Let me know if you have any issues and thanks for bringing it to my attention.
