### ISSUE TITLE
Does the script check if the Company Portal app is already installed? What would happen if I deploy Company Portal app via Line of Business app and also with a script?

### ISSUE THREAD

**Issue by InsulT** [microsoft/shell-intune-samples#20]

**Comment by theneiljohnson** [comment]
The default behaviour is that it will detect that Company Portal is already installed and do nothing. The behaviour is set by the autoUpdate="true" variable. If you change this to autoUpdate="false" the script will  overwrite the Company Portal application if it's already installed.

**Comment by theneiljohnson** [comment]
The default behaviour is that it will detect that Company Portal is already installed and do nothing. The behaviour is set by the autoUpdate="true"   variable. If you change this to autoUpdate="false" the script will
