### ISSUE TITLE
Commented out code?

### ISSUE THREAD

**Issue by BigIve** [microsoft/shell-intune-samples#21]
Hi,
I've been testing this script and noticed that **Line 78** ([in the downgrade end-user script](https://github.com/microsoft/shell-intune-samples/blob/master/Misc/Manage%20Accounts/downgradeUsertoStandard.sh)) appears to have been commented out.  Is this 'by design' (a safety feature maybe?).  As once I uncommented this line the script ran successfully on my test macOS device and downgraded the end-user to a standard one during an ADE (via Intune).
Many thanks for making the script available, it has helped resolve an issue for a customer of mine.

**Comment by theneiljohnson** [comment]
This is by design so avoid accidental damage to your environment.
