### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jste0001** [microsoft/shell-intune-samples#22]
Hi,

I'm trying to use the Quick Run script in Terminal but I receive the following error:

"Wed 21 Jul 2021 11:56:43 BST | Installing Company Portal
installer: Error trying to locate volume at /Applications
Wed 21 Jul 2021 11:56:44 BST | Failed to install Company Portal"

I'm not knowledgeable about scripting so I looked into this and all I can gather is that it may be an issue with line 379:

` installer -pkg "$tempfile" -target /Applications `

and I think perhaps it may have to be this instead:

` installer -pkg "$tempfile" -target / `

As I said, this definitely isn't my specialty and could be wrong but am eager to try to get this working so I can deploy the Quick Run script to multiple devices.

Thanks!

**Comment by theneiljohnson** [comment]
Adding @Marc ***@***.***> who might be able to take a look before I'm back from leave.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: jste0001 ***@***.***>
Sent: Wednesday, July 21, 2021 12:27:40 PM
To: microsoft/shell-intune-samples ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/shell-intune-samples] Installation issue (#22)


Hi,

I'm trying to use the Quick Run script in Terminal but I receive the following error:

"Wed 21 Jul 2021 11:56:43 BST | Installing Company Portal
installer: Error trying to locate volume at /Applications
Wed 21 Jul 2021 11:56:44 BST | Failed to install Company Portal"

I'm not knowledgeable about scripting so I looked into this and all I can gather is that it may be an issue with line 379:

installer -pkg "$tempfile" -target /Applications

and I think perhaps it may have to be this instead:

installer -pkg "$tempfile" -target /

As I said, this definitely isn't my specialty and could be wrong but am eager to try to get this working so I can deploy the Quick Run script to multiple devices.

Thanks!

**Comment by mnahum** [comment]
@jste0001 I just tried the  script from a terminal window on a BigSur device and  the script is running as expected.(must be run as root)

Even if the -target parameter is mandatory, the majority of the package don't let the freedom to select where you want to install the application on macOS and as you shared in the majority of the case you will put "/" as a target ... so if it's working for you, don't hesitate to update the script.

**Comment by jste0001** [comment]
@mnahum I think I've made my own copy / repository and edited the script for me to play around with. If I've done anything wrong which has affected your repository then do let me know, I've not used GitHub before.
