### ISSUE TITLE
Not an issue, more like a question

### ISSUE THREAD

**Issue by InsulT** [microsoft/shell-intune-samples#23]
Hey Guys!

Thank you very much for this project, it helps a lot. I was wondering, have you ever tried to package Cisco AMP this way?

I have tried everything, but it will never install successfully :(

Thanks in advance!

**Comment by theneiljohnson** [comment]
Sorry, this isn’t something I have done. I did a bit of reading though and it looks like you should have a DMG that contains the package and dependencies supplied from the AMP console?

I think I’d approach this by scripting the download of the DMG, mounting it and then firing the package installer in silent mode. It looks like it should all run as root.

From: InsulT ***@***.***>
Date: Thursday, 22 July 2021 at 20:27
To: microsoft/shell-intune-samples ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/shell-intune-samples] Not an issue, more like a question (#23)

Hey Guys!

Thank you very much for this project, it helps a lot. I was wondering, have you ever tried to package Cisco AMP this way?

I have tried everything, but it will never install successfully :(

Thanks in advance!

**Comment by InsulT** [comment]
Hey Niel,

unfortunately the cisco amp is packaged in a really weird way. Its in a .dmg format, but it contains a .pkg file, which also contains a bunch of .pkg files. When I try to use your script that install it from a .pkg file I got an error something like: "installer has no access to that pkg file or access denied".

At this point I am kinda lost :(

Anyway, thanks for your reply.

**Comment by theneiljohnson** [comment]
Reach out to me at ***@***.*** and we can take a deeper look.

________________________________

**Comment by theneiljohnson** [comment]
I've had a look at this and produced an example script here : https://github.com/microsoft/shell-intune-samples/tree/master/Apps/Cisco%20AMP

**Comment by InsulT** [comment]
Many thanks Neil, I will check it ;)
