### ISSUE TITLE
Microsoft Office for MAC Autoupdate enable for all users

### ISSUE THREAD

**Issue by ehtesham1601** [microsoft/shell-intune-samples#24]
Hi, 

Is there a way to enable MAU for all users (change permissions) so that users do not have to manually do it or ask for.

**Comment by theneiljohnson** [comment]
Just so I understand, you have multiple users sharing the same device and you wan't MAU to automatically run under each users login and update files for everyone?

**Comment by ehtesham1601** [comment]
Yes correct.

**Comment by theneiljohnson** [comment]
I don't have time to test, but have a go with this https://github.com/microsoft/shell-intune-samples/blob/master/Apps/Cisco%20AMP/Cisco%20AMP%20Config%2011.x.mobileconfig

**Comment by theneiljohnson** [comment]
We think that this should work anyway. Just need to set AcknowledgedDataCollectionPolicy to 'RequiredDataOnly' in the plist and the end users shouldn't get prompted.

**Comment by theneiljohnson** [comment]
We think that this should work anyway. Just need to set AcknowledgedDataCollectionPolicy to 'RequiredDataOnly' in the plist and the end users shouldn't get prompted.
