### ISSUE TITLE
Cisco AMP Config.mobileconfig cannot be applied on Apple Silicon M1 devices

### ISSUE THREAD

**Issue by InsulT** [microsoft/shell-intune-samples#25]
Hello Neil,

we received a new M1 chipped MacBook and the custom profiles fail with 0x87d1271a error code.

Is there a workaround for that?

**Comment by theneiljohnson** [comment]
Sorry, I didn't get chance to test with an M1. Do you have any idea which part of the payload is failing? You might be quicker to open a support case with Cisco though, they'll probably have an updated mobileconfig for Apple Silicon devices.

**Comment by InsulT** [comment]
Ye, I got this error code in Intune: 0x87d1271a

According to the articles below, it has issues with applying Kernel extensions.
https://github.com/microsoft/mdatp-xplat/issues/7

https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-kernel-extensions-on-macs-running-apple-silicon-are/ba-p/2238727

https://support.apple.com/en-us/HT211860#silicon

But to be honest, I am not so experienced in macOS things :(

**Comment by theneiljohnson** [comment]
I don't have time to test, but have a go with this https://github.com/microsoft/shell-intune-samples/blob/master/Apps/Cisco%20AMP/Cisco%20AMP%20Config%2011.x.mobileconfig
