### ISSUE TITLE
Script on Old Macs

### ISSUE THREAD

**Issue by MWR-Napavine** [microsoft/shell-intune-samples#27]
According to the Microsoft website, the Company Portal app requires MacOS 10.12 or newer.

I checked, and I didn't see anything in the script that checks to make sure the current version of the OS is compatible.

So I checked to see if I can setup in Intune to only run the script with 10.12 or newer... but apparently that's not something scripts can be setup to do.

Is this an issue? We have a lot of older macs here, and I wanted to know before I deploy it to a bunch of them.

**Comment by theneiljohnson** [comment]
The sample script doesn't do any kind of OS version checking currently. Also, once macOS 12 ships the supportability line will move to 10.15 or newer for Intune too, so it's worth bearing that in mind.

I'll try and find time to add something to check that the OS is going to support Company Portal before we try and install it at some point though.

**Comment by MWR-Napavine** [comment]
Oh great. Even fewer of my Macs will work with InTune.
