### ISSUE TITLE
Failed to determine Temp file Type {}

### ISSUE THREAD

**Issue by PapaCoderNit** [microsoft/shell-intune-samples#31]
Im using the new script version 3.0.1.
im getting the error Failed to determine Temp file Type {}
Google drive and Adobereader worked with this but is not working with vonage

Its a .Dmg file then when opened has a .APP file

##############################################################
# Mon Nov 22 14:39:53 EST 2021 | Logging install of [Vonage Business] to [/Library/Logs/Microsoft/IntuneScripts/VonageBusiness/Vonage Business.log]
############################################################

Mon Nov 22 14:39:53 EST 2021 | Checking if we need Rosetta 2 or not
Mon Nov 22 14:39:53 EST 2021 | Waiting for other [/usr/sbin/softwareupdate] processes to end
Mon Nov 22 14:39:53 EST 2021 | No instances of [/usr/sbin/softwareupdate] found, safe to proceed
Mon Nov 22 14:39:53 EST 2021 | [Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz] found, Rosetta not needed
Mon Nov 22 14:39:53 EST 2021 | Checking if we need to install or update [Vonage Business]
Mon Nov 22 14:39:53 EST 2021 | [Vonage Business] not installed, need to download and install
Mon Nov 22 14:39:53 EST 2021 | Dock is here, lets carry on
Mon Nov 22 14:39:53 EST 2021 | Starting downlading of [Vonage Business]
Mon Nov 22 14:39:53 EST 2021 | Waiting for other [curl -f] processes to end
Mon Nov 22 14:39:53 EST 2021 | No instances of [curl -f] found, safe to proceed
Mon Nov 22 14:39:53 EST 2021 | Downloading Vonage Business
Mon Nov 22 14:39:55 EST 2021 | Found DMG, looking inside...
Mon Nov 22 14:39:55 EST 2021 | Mounting Image
Mon Nov 22 14:39:55 EST 2021 | Un-mounting [/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.q6OHFnBu/Vonage Business]
Failed to determine temp file type []
mactest@MacTests-Mac-mini Vonage % 

# User Defined variables
weburl="https://vbc-downloads.vonage.com/mac/VonageBusinessSetup.dmg"              # What is the Azure Blob Storage URL?
appname="Vonage Business"                                                        # The name of our App deployment script (also used for Octory monitor)
app="Vonage Business.app"                                                        # The actual name of our App once installed
logandmetadir="/Library/Logs/Microsoft/IntuneScripts/VonageBusiness"             # The location of our logs and last updated data
processpath="/Applications/Vonage Business.app/Contents/MacOS/Vonage Business"      # The process name of the App we are installing
terminateprocess="true"                                                       # Do we want to terminate the running process? If false we'll wait until its not running
autoUpdate="true"                                                             # Application updates itself, if already installed we should exit

**Comment by PapaCoderNit** [comment]
Any update??

**Comment by asman2maani** [comment]
Im also having this issue... what was the fix????


Tue Jul 26 16:50:01 CDT 2022 | Checking if we need Rosetta 2 or not Tue Jul 26 16:50:01 CDT 2022 | Waiting for other [/usr/sbin/softwareupdate] processes to end Tue Jul 26 16:50:01 CDT 2022 | No instances of [/usr/sbin/softwareupdate] found, safe to proceed Tue Jul 26 16:50:01 CDT 2022 | Intel processor installed. No need to install Rosetta. Tue Jul 26 16:50:01 CDT 2022 | Checking if we need to install or update [Sophos] Tue Jul 26 16:50:01 CDT 2022 | [Sophos] not installed, need to download and install Tue Jul 26 16:50:01 CDT 2022 | Dock is here, lets carry on Tue Jul 26 16:50:01 CDT 2022 | Starting downlading of [Sophos] Tue Jul 26 16:50:01 CDT 2022 | Waiting for other [curl -f] processes to end Tue Jul 26 16:50:02 CDT 2022 | No instances of [curl -f] found, safe to proceed Tue Jul 26 16:50:02 CDT 2022 | Downloading Sophos [shorturl.at/gioDL] Tue Jul 26 16:50:04 CDT 2022 | Unknown file type [/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.ioYWjWy5/gioDL], analysing metadata Failed to determine temp file type [/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.ioYWjWy5/gioDL: HTML document text, Unicode text, UTF-8 text, with very long lines (7729)]
