### ISSUE TITLE
Help with enable "Remote Management" 

### ISSUE THREAD

**Issue by ehtesham1601** [microsoft/shell-intune-samples#32]
Hi, I have been struggling to setup remote management on Big Sur and above (Apple Silicon), getting the below error 

"setremotelogin: Turning Remote Login on or off requires Full Disk Access privileges."

I am using the below command to enable Remote management 

sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -allowaccessfor -specifiedusers -users administrator -on -privs -all -restart -agent -menu

Can someone help please.

**Comment by ehtesham1601** [comment]
@theneiljohnson could you please look into this.

**Comment by theneiljohnson** [comment]
Apple has made this quite difficult. We're currently investigating doing this via MDM command. I'm going to remove this script for now and close this because I don't think there is much that we can do.
