### ISSUE TITLE
MPKG Files are not supported

### ISSUE THREAD

**Issue by MCsquare10** [microsoft/shell-intune-samples#38]
MPKG files are not supported, is it possible to support this file type.

Error below:
"Detected both APP and PKG in same DMG, exiting gracefully Wed Feb 2 07:51:30 EST 2022 | Un-mounting [/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.q8EamKtI/ Failed to determine temp file type []"

Thanks.

**Comment by skares** [comment]
This is a real issue for us . too. Please support these kind of packages.

**Comment by theneiljohnson** [comment]
Can you give me some examples that are provided as mpkg please and i'll add it to my list of things to look at.
