### ISSUE TITLE
Plist file name in installMDATPQuickScanJob.sh

### ISSUE THREAD

**Issue by wesleyhigh9thwonder** [microsoft/shell-intune-samples#39]
Hi, you have the plist file name for the scheduled scans as: com.microsoft.**mdatp**.schedquickscan.plist where the official documentation has com.microsoft.**wdav**.schedquickscan.plist listed as the file path. [https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-schedule-scan?view=o365-worldwide#schedule-a-scan-with-intune](url) 

Not sure if both work or not.

**Comment by theneiljohnson** [comment]
It shouldn't matter, it's just to identify the launch daemon. I'll update anyway though.
