### ISSUE TITLE
installRosetta2.sh is reinstalling rosetta even if it is already installed

### ISSUE THREAD

**Issue by c-orlik** [microsoft/shell-intune-samples#42]
Line 74 does not work anymore on Monterey (at least 12.2.1, maybe on older versions as well) since the plist file is not existing anymore.
Better check for installed rosetta would be to check if the oahd deamon is running:
if [ ! `pgrep oahd` ]; then

**Comment by theneiljohnson** [comment]
Thanks for picking this up. I updated all of the other samples a little while back but forgot this one!
