### ISSUE TITLE
tbz2 files are not supported

### ISSUE THREAD

**Issue by denis111** [microsoft/shell-intune-samples#43]
I guess it would be almost the same as zip files.

**Comment by theneiljohnson** [comment]
Hi Denis, what are you trying to achieve exactly?

**Comment by denis111** [comment]
Sorry for such a brief issue text. I mean support of installing apps from *.tbz2/*.tar.bz2 files like https://imageoptim.com/ImageOptim1.8.9a1.tar.bz2 . I've seen some app also packaged with tbz2 extension. For now only dmg, pkg and zip are supported. Si I guess it's almost identical to zip, only changing the command to extract archive.

**Comment by theneiljohnson** [comment]
See if this works. I've added in the detection logic and uncompressing but this isn't a file format I've seen many apps come in so have only been able to test with the one so far.

https://github.com/microsoft/shell-intune-samples/tree/master/Apps/ImageOptim
