### ISSUE TITLE
App installs with dmg

### ISSUE THREAD

**Issue by cashxx** [microsoft/shell-intune-samples#44]
In the install app scripts using dmg I have noticed some issues lately with dmg files with EULA's.  Not sure how to get around this.  I think for a small EULA you can put     yes | hdiutil .........     but having issues with multipage EULA's and getting to the end to have it take the yes.  Example is BrightAuthor:Connected from brightsign.biz

**Comment by theneiljohnson** [comment]
Yeah, this is a limitation. If you find a way around it feel free to check in an update.
