### ISSUE TITLE
Rosetta Install Script error

### ISSUE THREAD

**Issue by aljfoster** [microsoft/shell-intune-samples#50]
I am trying to deploy the Rosetta Install script on an M1 MacBook Pro 16 inch and the script gets an error on line 77.  
/bin/bash: line 77: waitForProcess: command not found
softwareupdate: invalid option -- ?
softwareupdate: invalid option -- ?
softwareupdate: invalid option -- ?
softwareupdate: invalid option -- n
softwareupdate: invalid option -- s
softwareupdate: invalid option -- t
softwareupdate: unrecognized option `--rosetta'
softwareupdate: invalid option -- ?
softwareupdate: invalid option -- ?
softwareupdate: invalid option -- ?
softwareupdate: invalid option -- g
softwareupdate: invalid option -- e
softwareupdate: invalid option -- e
softwareupdate: unrecognized option `--to-license'
usage: softwareupdate <cmd> [<args> ...]

I am thinking that this Mac no longer includes the command waitForProcess.  Anyone else having this issue?

**Comment by theneiljohnson** [comment]
Not quite sure what happened to this script. I've fixed it now though, so give it another try.
