### ISSUE TITLE
Yammer script deprecated

### ISSUE THREAD

**Issue by iainfm** [microsoft/shell-intune-samples#58]
I _think_ the Yammer app has been removed by Microsoft in favour of using the browser-based interface.

The weburl in the sample script (https://aka.ms/yammer_desktop_mac) no longer points to an installer, and simply redirects to Bing, so the Yammer script may be redundant.

**Comment by theneiljohnson** [comment]
Thanks, i've confirmed with the team. We should be using the PWA app or the web app so i'll remove this for now.
