### ISSUE TITLE
Default Browser

### ISSUE THREAD

**Issue by poindexter6** [microsoft/shell-intune-samples#65]
I would love to see a way to set the default web browser. For instance, I would prefer if all my users set their default browser to Edge (for password and bookmark syncing reasons). I'm already successfully installing Edge, would be nice if after edge was downloaded and installed, it set Edge as the default.

**Comment by theneiljohnson** [comment]
The easiest way I know to do this is by setting the Edge plist to ‘Set Microsoft Edge as default browser’ to enabled. This will prompt the end user to click the button on launch. The Edge configuration is available natively in the Intune Device Configuration settings picker.

From: poindexter6 ***@***.***>
Date: Thursday, 28 July 2022 at 16:35
To: microsoft/shell-intune-samples ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/shell-intune-samples] Default Browser (Issue #65)

I would love to see a way to set the default web browser. For instance, I would prefer if all my users set their default browser to Edge (for password and bookmark syncing reasons). I'm already successfully installing Edge, would be nice if after edge was downloaded and installed, it set Edge as the default.
