### ISSUE TITLE
Nudge script is downloading a hardcoded version instead of the latest.

### ISSUE THREAD

**Issue by rnicolson** [microsoft/shell-intune-samples#69]
Script is downloading the 1.1.7.81411 version. Changing the weburl to something like the following should ensure it always grabs the latest.

nudgeLatestURL="https://github.com/macadmins/nudge/releases/latest/"
versionUrl=$(curl "${nudgeLatestURL}" -s -L -I -o /dev/null -w '%{url_effective}')
versionNumber=$(printf "%s" "${versionUrl[@]}" | sed 's@.*/@@' | sed 's/%20/-/g')
versionNumber=${versionNumber:1}
weburl="https://github.com/macadmins/nudge/releases/download/v$versionNumber/Nudge_Suite-$versionNumber.pkg"

**Comment by theneiljohnson** [comment]
Thanks, finally got around to implementing this.
https://github.com/microsoft/shell-intune-samples/tree/master/macOS/Apps/Nudge
