### ISSUE TITLE
Rqpid7 install (token install)

### ISSUE THREAD

**Issue by Alfa128** [microsoft/shell-intune-samples#70]
Thx for all your work, looking a way to deploy rapid7 agent on mac (token install) via intune.

Would like to use existing template but i dont see any function to run .sh script with parameters.(only pkg dmg and zip seems supported)

Idea would be to download sh installer from an azure blob and run the install command with parameters that includes my enterprise token

**Comment by theneiljohnson** [comment]
Just download the script from Blob with curl to a known location and then run by using

. /tmp/somescript.sh param1 param2

From: Alfa128 ***@***.***>
Date: Sunday, 2 October 2022 at 11:25
To: microsoft/shell-intune-samples ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/shell-intune-samples] Rqpid7 install (token install) (Issue #70)

Thx for all your work, looking a way to deploy rapid7 agent on mac (token install) via intune.

Would like to use existing template but i dont see any function to run .sh script with parameters.(only pkg dmg and zip seems supported)

Idea would be to download sh installer from an azure blob and run the install command with parameters that includes my enterprise token
