### ISSUE TITLE
Visual Studio Code not installed as Universal App

### ISSUE THREAD

**Issue by mateusz-int** [microsoft/shell-intune-samples#79]
The VS Code [script](https://github.com/microsoft/shell-intune-samples/blob/master/Apps/Visual%20Studio%20Code/installVSCode.sh) does not install the app as "Universal App". The app is installed as "Application (Intel)". Would be great to fix this as there should be power and performance optimization.

**Comment by theneiljohnson** [comment]
Changed URL to universal binary - https://github.com/microsoft/shell-intune-samples/tree/master/macOS/Apps/Visual%20Studio%20Code
