### ISSUE TITLE
Github Desktop installation script does not work

### ISSUE THREAD

**Issue by mateusz-int** [microsoft/shell-intune-samples#85]
https://github.com/microsoft/shell-intune-samples/blob/master/macOS/Apps/gitHub%20Desktop/installGitHubDesktop.sh

Auto-update should be set to "true".

When URL changed to ARM app version - it is not possible to lunch the app as error occur.
<img width="262" alt="Screenshot 2022-12-17 at 10 29 05" src="https://user-images.githubusercontent.com/118596084/208235489-1e887312-6ea6-4639-8e88-5125ffa9585e.png">

Manual installation process works correctly.

**Comment by theneiljohnson** [comment]
Can you take a look at the sample now please? I've modified a little to handle this a bit better.

**Comment by theneiljohnson** [comment]
Closing this, it was resolved by adding dot_clean after the copy routine
