### ISSUE TITLE
Add Apps to Dock script does not work

### ISSUE THREAD

**Issue by mateusz-int** [microsoft/shell-intune-samples#86]
https://github.com/microsoft/shell-intune-samples/blob/master/macOS/Config/Dock/addAppstoDock.sh

After the execution Dock crashes and default values are restored. Company Portal starts correctly.
<img width="1361" alt="Screenshot 2022-12-17 at 10 35 16" src="https://user-images.githubusercontent.com/118596084/208235682-dfe2454e-2a24-4673-823a-4277e56af0c1.png">

MacOS version: 13.1

**Comment by theneiljohnson** [comment]
Are you running this as root or the end user?

**Comment by pishah** [comment]
Awe, let me try that. Thank you. I will try to find the log, sorry new to MacOS haha

**Comment by pishah** [comment]
That did the trick thank you! In the terminal when I was using other commands I needed the \ for some reason so thought it was necessary here too. Really appreciate you making this!
