### ISSUE TITLE
Edge Failing to Download

### ISSUE THREAD

**Issue by kingpocket** [microsoft/shell-intune-samples#92]
If I manually browse to the URL in the script, Edge successfully downloads, but it keeps failing from the script.

##############################################################
# Fri Feb 10 10:42:23 EST 2023 | Logging install of [Microsoft Edge] to [/Library/Logs/Microsoft/IntuneScripts/installEdge/Microsoft Edge.log]
############################################################

Fri Feb 10 10:42:23 EST 2023 | Checking if we need Rosetta 2 or not
Fri Feb 10 10:42:23 EST 2023 | Waiting for other [/usr/sbin/softwareupdate] processes to end
Fri Feb 10 10:42:23 EST 2023 | No instances of [/usr/sbin/softwareupdate] found, safe to proceed
Fri Feb 10 10:42:23 EST 2023 | Rosetta is already installed and running. Nothing to do.
Fri Feb 10 10:42:23 EST 2023 | Checking if we need to install or update [Microsoft Edge]
Fri Feb 10 10:42:23 EST 2023 | [Microsoft Edge] not installed, need to download and install
Fri Feb 10 10:42:23 EST 2023 | Dock is here, lets carry on
Fri Feb 10 10:42:23 EST 2023 | Starting downlading of [Microsoft Edge]
Fri Feb 10 10:42:23 EST 2023 | Waiting for other [curl -f] processes to end
Fri Feb 10 10:42:23 EST 2023 | No instances of [curl -f] found, safe to proceed
Fri Feb 10 10:42:23 EST 2023 | Downloading Microsoft Edge
Fri Feb 10 10:42:23 EST 2023 | Failure to download [https://go.microsoft.com/fwlink/?linkid=2093504] to []

**Comment by MarkHowe86** [comment]
I am also experiencing this. I have even tried different download links but same issue. Do we have fix?

**Comment by theneiljohnson** [comment]
Looks like curl was failing to generate a local file name for the download. I've attempted to fix by setting it manually. Seems to work for me, but please test and let me know.

**Comment by kingpocket** [comment]
It just worked for me.  Thank you!
